### PR TITLE
chore: update CI action versions

### PR DESCRIPTION
**Pull request by mxdvl**
And link Node’s version to the one in repo

### CODE REVIEW

**Comment by RoelN** [comment]
@mxdvl Thanks for your PR! Currently the CI is failing on all kinds of Prettier warnings. Are these a side effect of your changes?

**Comment by mxdvl** [comment]
It must be, somehow, but I'm not sure why… ☹️

**Comment by Ryuno-Ki** [comment]
`node_modules/.bin/prettier --write .` edits a bunch of files here when I check out your branch, @mxdvl

**Comment by RoelN** [comment]
I'm okay with the changes Prettier suggests. As long as the codebase is consistent. Can we let Prettier just fix them?

**Comment by RoelN** [comment]
Also I wonder if this PR will run into the same ssh/https trouble as seen here: https://github.com/Wakamai-Fondue/wakamai-fondue-site/actions/runs/11230829820/job/31218950314?pr=185

I'm trying to fix that here: https://github.com/Wakamai-Fondue/wakamai-fondue-site/pull/187 The problem is apparently that we used to load the Engine dependency over ssh while developing it before making everything public. Since the repo is public now we can just load it over https instead of ssh. My commit there seems to fix that particular error, now stranding on another. Oh well, diving into that one now!

**Comment by mxdvl** [comment]
> `node_modules/.bin/prettier --write .` edits a bunch of files here when I check out your branch, @mxdvl

> I'm okay with the changes Prettier suggests. As long as the codebase is consistent. Can we let Prettier just fix them?

Thanks both, have done so in 4a95abdccefd2e268a6b0eba7baca55f84f8a63b

**Comment by RoelN** [comment]
@mxdvl I get the error

```
npm ERR! Missing script: "lint:check"
```

Is that something that you added but didn't commit?

**Comment by RoelN** [comment]
Oh I just noticed https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/66 which might be relevant?

**Comment by RoelN** [comment]
Making progress! \o/

I see it now complains about filenames, which could be fixed by cherry-picking https://github.com/Wakamai-Fondue/wakamai-fondue-site/pull/187/commits/5a9bdec33e987c5ad94f5c8ca86c4e8a7f153fb8 where @Ryuno-Ki addressed this. Let's do this, and then when this PR is green, rebase it against the other PRs?

**Comment by mxdvl** [comment]
> Oh I just noticed [Wakamai-Fondue/wakamai-fondue-engine#66](https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/66) which might be relevant?

This is another approach that we could go with, using a matrix of Node versions, but I think that having a consistent version locally and on CI is a simpler first step.

**Comment by RoelN** [comment]
Ha! Nice, we're at the old zlib/fs error, which will be addressed in @Ryuno-Ki's PR!

If nobody objects, perhaps we can get this merged into the master, then rebase the master in your branch, @Ryuno-Ki?

**Comment by Ryuno-Ki** [comment]
Coolio. Now @RoelN has to decide to either adopt #184 or #185.

I vote for merging this PR and continue there.

(what a :yarn: of issues :fearful: )

**Comment by Ryuno-Ki** [comment]
Thanks, @mxdvl !

**Comment by RoelN** [comment]
And... done!!

Thanks @mxdvl and @Ryuno-Ki for your help, it is much appreciated!

**Pull request merged**
