### PR TITLE
Trying to fix CI for #185

### PR DESCRIPTION
**Pull request by RoelN**
Based on https://github.com/Wakamai-Fondue/wakamai-fondue-site/pull/185

Changing the `package-lock.json` to fetch from `https` instead of `ssh`, since the repos are now public.

### CODE REVIEW

**Comment by RoelN** [comment]
Okay, now the error is for missing `assert` which, according to some duckduckgoing, is fixable by simply upgrading to a newer Node.

Fingers crossed!

**Comment by Ryuno-Ki** [comment]
Can you rebase? I believe to have catched this in #185.

**Comment by RoelN** [comment]
@Ryuno-Ki I think we can delete this. I was editing the lockfile directly in an attempt to get _something_ working, but this doesn't look like the way to go. I'll try to upgrade Node and restart this quest in another PR!

**Comment by Ryuno-Ki** [comment]
Skyrim Meme saying „I'll finish the main quest today -- oh look, a side quest”

**Pull request closed without merging**
