### PR TITLE
Add hinting info, update reference to engine

### LINKED ISSUE #20: [ENGINE] Detect if font is hinted
As featurerequested here https://www.zachleat.com/web/css-tricks-web-fonts/

### PR DESCRIPTION
**Pull request by RoelN**
Fixes #20 :-)

### CODE REVIEW

**Comment by pascalw** [comment]
@RoelN build is failing. WF engine doesn't current transpile it's code, we're relying on WF site to do that. It seems lib-font has added some new syntax that the WF site Webpack/Babel can't handle currently. I'll add a loader to the WF site for now, but we might want to think about transpiling in WF-engine to make this easier for consumers of that library.

**Comment by RoelN** [comment]
@pascalw Ah thanks for spotting this! I didn't know that, so I was updating the dependencies in an attempt to make the error go away (see latest commit).

**Comment by pascalw** [comment]
@RoelN build is back to green again. Problem was that we were already having Babel transpile the wf engine dependency, but now `lib-font` is a separate dependency that code wasn't transpiled. I've updated the Babel config to transpile `lib-font` too.

**Comment by RoelN** [comment]
@pascalw Thanks a lot! We're good to merge, if you agree?

**Review by pascalw — APPROVED** [review]

**Comment by pascalw** [comment]
Yep! 👍

**Pull request merged**
