### PR TITLE
Vue updates

### PR DESCRIPTION
**Pull request by RoelN**

### CODE REVIEW

**Comment by RoelN** [comment]
It looks like I can drop a font, and then get past the Vue errors with this PR.

This is not to say that everything is fixed, it just means the site is now choking on something in the engine 🤣

@Ryuno-Ki or @mxdvl, if interested, would you want to do a review?

**Review by mxdvl — COMMENTED** [review]
Unfortunately, my Vue knowledge is limited so I would not feel confident weighing in.

**Comment by RoelN** [comment]
@danieldiekmeier Thanks! Yeah, I have all those warnings on my list for tomorrow. I missed that `toggleModal` stuff in the previous update — thanks for catching it!

**Comment by RoelN** [comment]
I'll merge this now so it's easier to work from, if anyone wants to branch off and dive it!

**Pull request merged**
